name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.14
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build shadowJar for Github
        run: ./gradlew -Prelease -Pversion=${{ steps.get_tag.outputs.VERSION }} shadowJar createChecksums
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/secret-provider-${{ steps.get_tag.outputs.VERSION }}-all.jar
            build/libs/secret-provider-${{ steps.get_tag.outputs.VERSION }}-all.jar.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

